### ISSUE TITLE
Extract iltorb binary into a separate package

### ISSUE THREAD

**Issue by Kikobeats** [alixaxel/lambdafs#1]
If you are using `lambdafs` and `chrome-aws-lambda`, you have two binaries for doing the same.

That's mainly happened because the iltorb binary compatible with AWS Lambda is living with the code:

- https://github.com/alixaxel/lambdafs/tree/master/source/iltorb
- https://github.com/alixaxel/chrome-aws-lambda/tree/master/source/iltorb

Ideally, this could be extracted into a `iltorb-lambda` package and be used by both dependencies.

**Comment by alixaxel** [comment]
I've removed the bundled `iltorb` from `chrome-aws-lambda`, it now uses this package directly.
